# Default configuration for or1k-softmmu

CONFIG_SERIAL=y
CONFIG_OPENCORES_ETH=y
CONFIG_OMPIC=y
CONFIG_LITEX=y
CONFIG_FRAMEBUFFER=y
CONFIG_PTIMER=y
CONFIG_SD=y

CONFIG_I2C=y
CONFIG_SSI=y
CONFIG_SSI_M25P80=y
